VAGRANTFILE_API_VERSION = "2"
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.provider :libvirt do |libvirt|
     # Enable KVM nested virtualization
     libvirt.nested = true
     libvirt.cpu_mode = "host-model"
  end
  # config.vm.provider :virtualbox do |vb|
  #   vb.customize ["modifyvm", :id, "--memory", "4096"]
  #   vb.customize ["modifyvm", :id, "--cpus", "1"]
  #   # Enable KVM nested virtualization
  #   libvirt.nested = true
  #   libvirt.cpu_mode = "host-model"
  # end
  # Provision with shell script and local files.
  # config.vm.provision "shell", path: "coldstart.sh"
  config.vm.synced_folder "./", "/vagrant", owner: "vagrant", group: "vagrant", :mount_options => ["ro"]
  config.vm.synced_folder "../tests", "/opt/tests", owner: "vagrant", group: "vagrant", :mount_options => ["ro"]
  config.vm.synced_folder "../salt/cloud.profiles.d", "/etc/salt/cloud.profiles.d", owner: "root", group: "root", :mount_options => ["ro"]
  config.vm.synced_folder "../salt/cloud.providers.d", "/etc/salt/cloud.providers.d", owner: "root", group: "root", :mount_options => ["ro"]
  config.vm.synced_folder "../salt/master.d", "/etc/salt/master.d", owner: "root", group: "root", :mount_options => ["ro"]
  config.vm.synced_folder "../salt/states", "/srv/salt", owner: "root", group: "root", :mount_options => ["ro"]
  config.vm.synced_folder "../salt/pillar", "/srv/pillar", owner: "root", group: "root", :mount_options => ["ro"]
  config.vm.synced_folder "../greenwebauth", "/opt/greenwebauth", owner: "root", group: "root", :mount_options => ["ro"] 
  # Have a static IP
  config.vm.network "private_network", ip: "172.30.1.5"
  # config.vm.network "forwarded_port", guest: 80, host: 8000
  # config.vm.network "forwarded_port", guest: 443, host: 8443
end
