set timeout 3
spawn telnet postfix.greenweb.ca 25
send "EHLO vmhost.greenweb.ca\r"
expect "mail.greenweb.ca"
send "MAIL FROM: <fakename@fakedomain.fake>\r"
expect "Ok"
send "RCPT TO:<postmaster@greenweb.ca>\r"
expect "Ok"
send "DATA\r"
expect "354"
send "From: Bogus <bogus@bogus.com>\r"
send "Subject: The Next Meeting\r"
send "To: john@mail.com\r"
send "\r"
send "Hi John,\r"
send "The next meeting will be on Friday.\r"
send "\r"
send "Bye!\r"
send "Bogus\r"
send ".\r"
expect "queued"
send "QUIT\r"
expect "Bye"
