
# Do open ldap modify to enable these users.
# Then connect to the users and delete all their emails.

set timeout 60

stty -echo
send_user -- "Password for cn=admin,dc=greenweb,dc=ca: "
expect_user -re "(.*)\n"
send_user "\n"
stty echo
set pass $expect_out(1,string)

set timeout 5

spawn ldapmodify -x -D cn=admin,dc=greenweb,dc=ca -H ldap://ldap.greenweb.ca -w "$pass"
send "dn: cn=test@greenweb.ca,ou=email,dc=greenweb,dc=ca\r"
send "changetype: modify\r"
send "replace: mailEnabled\r"
send "mailEnabled: TRUE\r"
send "\r"
send "dn: cn=quotatest@greenweb.ca,ou=email,dc=greenweb,dc=ca\r"
send "changetype: modify\r"
send "replace: mailEnabled\r"
send "mailEnabled: TRUE\r"
send "\r"
send \x04

expect "modifying entry \"cn=test@greenweb.ca,ou=email,dc=greenweb,dc=ca\""
expect "modifying entry \"cn=quotatest@greenweb.ca,ou=email,dc=greenweb,dc=ca\""

spawn openssl s_client -connect postfix.greenweb.ca:995 -quiet
expect "ready."
send "USER quotatest@greenweb.ca\r"
expect "OK"
send "PASS quotatest\r"
expect "OK"
send "STAT\r"
expect "OK"
expect -re "(\[0-9\]+) +\[0-9\]+\r"
set messages $expect_out(1,string)
send_user "Deleting quotatest's $messages messages.\r"
for {set i 1} {$i <= $messages} {incr i 1} {
    send "DELE $i\r"
    expect "OK"
}
send "QUIT\r"

spawn openssl s_client -connect postfix.greenweb.ca:995 -quiet
expect "ready."
send "USER test@greenweb.ca\r"
expect "OK"
send "PASS test\r"
expect "OK"
send "STAT\r"
expect "OK"
expect -re "(\[0-9\]+) +\[0-9\]+\r"
set messages $expect_out(1,string)
send_user "Deleting quotatest's $messages messages.\r"
for {set i 1} {$i <= $messages} {incr i 1} {
    send "DELE $i\r"
    expect "OK"
}
send "QUIT\r"

# Don't automatically accept vmhost's helos...
exec sudo lxc-attach --name=postfix -- sed -i "s/^ \\( *\\)permit_mynetworks # This must be commented out for vmhost's tests to work./#\\1permit_mynetworks # This must be commented out for vmhost's tests to work./" /etc/postfix/main.cf

exec sudo lxc-attach --name=postfix -- systemctl restart postfix

