set timeout 5
spawn telnet postfix.greenweb.ca 25
send "EHLO postfix.greenweb.ca\r"
send "MAIL FROM: <postmaster@greenweb.ca>\r"
send "RCPT TO:<postmaster@greenweb.ca>\r"
send "DATA\r"
send "From: Bogus <bogus@bogus.com>\r"
send "Subject: The Next Meeting\r"
send "To: john@mail.com\r"
send "\r"
send "Hi John,\r"
send "The next meeting will be on Friday.\r"
send "\r"
send "Bye!\r"
send "Bogus\r"
send ".\r"
expect "queued" { pass "Mail was successfully queued." } \
       timeout { fail "Mail was not sent." }
send "QUIT\r"
expect "Bye"
