
# Do open ldap modify to enable these users.
# Then connect to the users and delete all their emails.

set timeout 60

stty -echo
send_user -- "Password for cn=admin,dc=greenweb,dc=ca: "
expect_user -re "(.*)\n"
send_user "\n"
stty echo
set pass $expect_out(1,string)

set timeout 5

spawn ldapmodify -x -D cn=admin,dc=greenweb,dc=ca -H ldap://ldap.greenweb.ca -w "$pass"
send "dn: cn=test@greenweb.ca,ou=email,dc=greenweb,dc=ca\r"
send "changetype: modify\r"
send "replace: mailEnabled\r"
send "mailEnabled: FALSE\r"
send "\r"
send "dn: cn=quotatest@greenweb.ca,ou=email,dc=greenweb,dc=ca\r"
send "changetype: modify\r"
send "replace: mailEnabled\r"
send "mailEnabled: FALSE\r"
send "\r"
send \x04

expect "modifying entry \"cn=test@greenweb.ca,ou=email,dc=greenweb,dc=ca\""
expect "modifying entry \"cn=quotatest@greenweb.ca,ou=email,dc=greenweb,dc=ca\""
