{
 "title": "System",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Gigabytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1073741824" ], "type": "math" },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/ 1073741824" ], "type": "math" },
       { "params": [ "Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Idle Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Percentage" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_idle\") FROM \"autogen\".\"cpu\" WHERE $timeFilter GROUP BY time($__interval), \"cpu\" fill(linear)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "idle" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Gigabytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"free\") FROM \"autogen\".\"mem\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1073741824" ], "type": "math" },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1073741824" ], "type": "math" },
       { "params": [ "available" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}