set timeout 5

# Generate a randomish IP and attack with it.
set IP "192.255.255.[expr {int(rand()*255)}]"
spawn logger --id=666 -t sshd "Failed password for root from $IP port 37940 ssh2"
spawn logger --id=666 -t sshd "Failed password for root from $IP port 37940 ssh2"
spawn logger --id=666 -t sshd "Failed password for root from $IP port 37940 ssh2"
spawn logger --id=666 -t sshd "Failed password for root from $IP port 37940 ssh2"
spawn logger --id=666 -t sshd "Failed password for root from $IP port 37940 ssh2"
sleep 2

# Make sure it got banned by fail2ban.
spawn sudo fail2ban-client status sshd
expect "Banned IP list:"
expect $IP { pass "Fail2ban has blocked sshd user $IP." } \
    timeout { fail "Fail2ban may not have blocked sshd user $IP." } \
    eof { fail "Fail2ban may not have blocked sshd user $IP." }

# TODO Check that an email was received by test@greenweb.ca
# TODO Check that NFTables were updated
# TODO Figure out what this "Flush ticket(s) with iptables-multiport" is all about...
# why does fail2ban only let me have one port banned?
