set timeout 5

spawn logger --id=666 -t sshd "Failed password for root from 192.255.255.10 port 37940 ssh2"
spawn logger --id=666 -t sshd "Failed password for root from 192.255.255.10 port 37940 ssh2"
spawn logger --id=666 -t sshd "Failed password for root from 192.255.255.10 port 37940 ssh2"
spawn logger --id=666 -t sshd "Failed password for root from 192.255.255.10 port 37940 ssh2"
spawn logger --id=666 -t sshd "Failed password for root from 192.255.255.10 port 37940 ssh2"

# Sometimes the message gets truncated... hopefully it's smart enough.... I can add sleeps
# but an attacker probably isn't going to be slow.

# spawn telnet postfix.greenweb.ca 25
# send "EHLO postfix.greenweb.ca\r"
# # Wait with an expect, for pipelining reasons.
# expect "mail.greenweb.ca"
# send "MAIL FROM: <personr@totallyfakedomainaaaa.ca>\r"
# send "RCPT TO:<testgroup@greenweb.ca>\r"
# expect "omain not found" { pass "Mail was blocked bad domain" } \
#        timeout { fail "mail wasn't blocked by bad domain." }
# send "QUIT\r"
# expect "Bye"

# less /var/log/remote/ubuntu2004/sshd.log

# "Failed password for vagrant from 127.0.0.1 port 37940 ssh2"
# This here is enough to simulate it from my local machine:

# But I wish I had a way to fake the hostname...
# I can probably use lxc-attach to do it.
