# Do openldap modify to disable the test@greenweb.ca users.
# Then delete all their emails.

set timeout 60

stty -echo
send_user -- "Password for cn=admin,dc=greenweb,dc=ca: "
expect_user -re "(.*)\n"
send_user "\n"
stty echo
set pass $expect_out(1,string)

set timeout 5

spawn ldapmodify -x -D cn=admin,dc=greenweb,dc=ca -H ldap://ldap.greenweb.ca -w "$pass"
send "dn: cn=test@greenweb.ca,ou=email,dc=greenweb,dc=ca\r"
send "changetype: modify\r"
send "replace: mailEnabled\r"
send "mailEnabled: FALSE\r"
send \x04

expect "modifying entry \"cn=test@greenweb.ca,ou=email,dc=greenweb,dc=ca\""

# Setup fail2ban back to it's usual state.

# Perform a log rotation...
spawn sudo lxc-attach --name=logging -- logrotate --force /etc/logrotate.d/

# Tell fail2ban to go back to postmaster@greenweb.ca
exec sudo sed -i "s/^destemail =.*\$/destemail = postmaster@greenweb.ca/" /etc/fail2ban/jail.d/customizations.local

# Go back to the default bantime.
exec sudo rm /etc/fail2ban/jail.d/one-hour-ban.conf

exec sudo systemctl restart fail2ban
sleep 3
# Clear all the jails
exec sudo fail2ban-client unban --all

# Test for liveness...
spawn sudo fail2ban-client ping
expect pong
